# -*- coding: utf-8 -*-
"""01_generate_source_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RbcTTPKnckpq055sYRr-VjbgoS1cuJT
"""

# IMPORTACIÓN DE LIBRERÍAS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import random


# ============================================================
# CONFIGURACIÓN DE SEMILLA
# ============================================================

# Fijamos una semilla para que los datos aleatorios generados
# sean reproducibles en cada ejecución.
SEED = 42

random.seed(SEED)
np.random.seed(SEED)


# ============================================================
# DEFINICIÓN DE RUTAS DEL PROYECTO
# ============================================================

# Carpeta raíz donde almacenaremos los archivos del proyecto.
BASE_PATH = Path("/content/retail_analytics_project")

# Carpeta RAW: contiene los datos originales antes de aplicar
# transformaciones o reglas de negocio.
RAW_PATH = BASE_PATH / "data" / "raw"

# Separamos los datasets por entidad.
STORES_PATH = RAW_PATH / "stores"
PRODUCTS_PATH = RAW_PATH / "products"
CUSTOMERS_PATH = RAW_PATH / "customers"
SALES_PATH = RAW_PATH / "sales"


# ============================================================
# CREACIÓN DE CARPETAS
# ============================================================

# Creamos todas las carpetas necesarias.
# parents=True crea también las carpetas padre si no existen.
# exist_ok=True permite ejecutar el código varias veces sin error.
for path in [
    STORES_PATH,
    PRODUCTS_PATH,
    CUSTOMERS_PATH,
    SALES_PATH
]:
    path.mkdir(parents=True, exist_ok=True)


# Validamos la ruta principal creada.
print(BASE_PATH)

# ============================================================
# CREACIÓN DEL MAESTRO DE TIENDAS
# ============================================================

# Definimos los datos maestros de las tiendas.
# Cada tupla representa una tienda con:
# ID, nombre, ciudad, región, fecha de apertura y tipo de tienda.
stores_data = [
    ("S001", "Madrid Centro", "Madrid", "Madrid", "2016-03-15", "PHYSICAL"),
    ("S002", "Madrid Norte", "Madrid", "Madrid", "2018-06-10", "PHYSICAL"),
    ("S003", "Barcelona Centro", "Barcelona", "Cataluña", "2017-02-20", "PHYSICAL"),
    ("S004", "Barcelona Diagonal", "Barcelona", "Cataluña", "2019-09-05", "PHYSICAL"),
    ("S005", "Valencia Centro", "Valencia", "Comunidad Valenciana", "2018-04-12", "PHYSICAL"),
    ("S006", "Sevilla Centro", "Sevilla", "Andalucía", "2017-10-01", "PHYSICAL"),
    ("S007", "Málaga Centro", "Málaga", "Andalucía", "2020-02-15", "PHYSICAL"),
    ("S008", "Bilbao Centro", "Bilbao", "País Vasco", "2019-05-20", "PHYSICAL"),
    ("S009", "Zaragoza Centro", "Zaragoza", "Aragón", "2018-11-11", "PHYSICAL"),
    ("S010", "Alicante Centro", "Alicante", "Comunidad Valenciana", "2020-07-01", "PHYSICAL"),
    ("S011", "Murcia Centro", "Murcia", "Región de Murcia", "2019-03-18", "PHYSICAL"),
    ("S012", "Granada Centro", "Granada", "Andalucía", "2021-01-12", "PHYSICAL"),
    ("S013", "Córdoba Centro", "Córdoba", "Andalucía", "2020-09-10", "PHYSICAL"),
    ("S014", "Valladolid Centro", "Valladolid", "Castilla y León", "2018-08-22", "PHYSICAL"),
    ("S015", "Vigo Centro", "Vigo", "Galicia", "2019-06-30", "PHYSICAL"),
    ("S016", "A Coruña Centro", "A Coruña", "Galicia", "2021-04-15", "PHYSICAL"),
    ("S017", "Gijón Centro", "Gijón", "Asturias", "2020-03-05", "PHYSICAL"),
    ("S018", "Oviedo Centro", "Oviedo", "Asturias", "2019-12-01", "PHYSICAL"),
    ("S019", "Palma Centro", "Palma", "Islas Baleares", "2021-06-12", "PHYSICAL"),
    ("S020", "Las Palmas Centro", "Las Palmas", "Canarias", "2020-05-25", "PHYSICAL"),
    ("S021", "Tenerife Centro", "Santa Cruz de Tenerife", "Canarias", "2021-08-18", "PHYSICAL"),
    ("S022", "Pamplona Centro", "Pamplona", "Navarra", "2019-04-04", "PHYSICAL"),
    ("S023", "Santander Centro", "Santander", "Cantabria", "2020-10-10", "PHYSICAL"),
    ("S024", "Salamanca Centro", "Salamanca", "Castilla y León", "2021-02-22", "PHYSICAL"),
    ("S025", "Toledo Centro", "Toledo", "Castilla-La Mancha", "2022-01-15", "PHYSICAL"),
    ("S026", "Badajoz Centro", "Badajoz", "Extremadura", "2021-11-03", "PHYSICAL"),
    ("S027", "Logroño Centro", "Logroño", "La Rioja", "2022-03-18", "PHYSICAL"),
    ("S028", "Girona Centro", "Girona", "Cataluña", "2020-06-07", "PHYSICAL"),
    ("S029", "Tarragona Centro", "Tarragona", "Cataluña", "2021-09-09", "PHYSICAL"),
    ("S030", "Almería Centro", "Almería", "Andalucía", "2022-05-20", "PHYSICAL"),

    # Tienda virtual utilizada para identificar las ventas online.
    ("S999", "Online Store", "ONLINE", "ONLINE", "2015-01-01", "ONLINE")
]


# ============================================================
# CREACIÓN DEL DATAFRAME
# ============================================================

# Convertimos la lista de tiendas en un DataFrame de Pandas
# y asignamos los nombres de las columnas.
stores_df = pd.DataFrame(
    stores_data,
    columns=[
        "store_id",
        "store_name",
        "city",
        "region",
        "opening_date",
        "store_type"
    ]
)


# ============================================================
# AJUSTE DE TIPOS DE DATOS
# ============================================================

# Convertimos opening_date de texto a tipo datetime para poder
# realizar posteriormente filtros y operaciones con fechas.
stores_df["opening_date"] = pd.to_datetime(stores_df["opening_date"])


# Mostramos las primeras filas para validar el resultado.
stores_df.head()

# ============================================================
# VALIDACIÓN DEL MAESTRO DE TIENDAS
# ============================================================

# Comprobamos el número total de tiendas generadas.
print("Número de tiendas:", len(stores_df))

# Validamos que store_id sea único para cada tienda.
# Devuelve True si no existen IDs duplicados.
print("IDs únicos:", stores_df["store_id"].is_unique)

print()

# Revisamos cuántas tiendas existen de cada tipo
# (PHYSICAL y ONLINE).
print(stores_df["store_type"].value_counts())

# ============================================================
# DEFINICIÓN DEL CATÁLOGO DE PRODUCTOS
# ============================================================

# Definimos las categorías principales y las subcategorías
# disponibles para generar el catálogo de productos.
product_catalog = {
    "Electronics": [
        "Smartphones",
        "Laptops",
        "Tablets",
        "Headphones",
        "Smartwatches"
    ],
    "Home": [
        "Kitchen",
        "Furniture",
        "Decoration",
        "Lighting",
        "Storage"
    ],
    "Sports": [
        "Fitness",
        "Running",
        "Cycling",
        "Football",
        "Outdoor"
    ],
    "Fashion": [
        "T-Shirts",
        "Shirts",
        "Trousers",
        "Shoes",
        "Jackets"
    ],
    "Beauty": [
        "Skincare",
        "Makeup",
        "Fragrances",
        "Haircare",
        "Bodycare"
    ]
}


# ============================================================
# DEFINICIÓN DE MARCAS POR CATEGORÍA
# ============================================================

# Asociamos a cada categoría un conjunto de marcas ficticias.
# Esto nos permitirá generar productos manteniendo coherencia
# entre la categoría del producto y su marca.
brands_by_category = {
    "Electronics": ["Nexa", "Voltix", "Orion", "PixelCore", "TechNova"],
    "Home": ["CasaNova", "NordHome", "LivingCo", "UrbanNest", "Decora"],
    "Sports": ["MoveUp", "SprintX", "ActivePro", "TrailOne", "FitCore"],
    "Fashion": ["NorthLine", "UrbanWear", "NovaStyle", "BasicLab", "ModeOne"],
    "Beauty": ["PureGlow", "Aura", "Dermalux", "Bloom", "Essentia"]
}

# ============================================================
# GENERACIÓN DEL MAESTRO DE PRODUCTOS
# ============================================================

# Número total de productos que queremos generar.
NUM_PRODUCTS = 1000

# Lista donde iremos almacenando cada producto generado.
products = []

for i in range(1, NUM_PRODUCTS + 1):

    # Seleccionamos aleatoriamente una categoría, una subcategoría
    # perteneciente a esa categoría y una marca compatible.
    category = random.choice(list(product_catalog.keys()))
    subcategory = random.choice(product_catalog[category])
    brand = random.choice(brands_by_category[category])

    # Generamos un identificador único con formato P0001, P0002...
    product_id = f"P{i:04d}"

    # Creamos un nombre de producto combinando marca,
    # subcategoría y un número aleatorio.
    product_name = (
        f"{brand} "
        f"{subcategory} "
        f"{random.randint(100, 999)}"
    )

    # Definimos rangos de coste distintos según la categoría
    # para generar precios más realistas.
    cost_ranges = {
        "Electronics": (30, 600),
        "Home": (5, 250),
        "Sports": (8, 180),
        "Fashion": (4, 120),
        "Beauty": (2, 80)
    }

    min_cost, max_cost = cost_ranges[category]

    # Generamos el coste unitario dentro del rango de su categoría.
    unit_cost = round(
        random.uniform(min_cost, max_cost),
        2
    )

    # Aplicamos un margen comercial aleatorio entre el 20% y el 70%.
    margin = random.uniform(0.20, 0.70)

    # Calculamos el precio base de venta a partir del coste y el margen.
    base_price = round(
        unit_cost * (1 + margin),
        2
    )

    # Aproximadamente el 95% de los productos estarán activos.
    active = random.random() < 0.95

    # Añadimos el producto generado a la lista.
    products.append(
        {
            "product_id": product_id,
            "product_name": product_name,
            "category": category,
            "subcategory": subcategory,
            "brand": brand,
            "unit_cost": unit_cost,
            "base_price": base_price,
            "active": active
        }
    )


# Convertimos la lista de productos en un DataFrame de Pandas.
products_df = pd.DataFrame(products)

# Mostramos las primeras filas para validar el resultado.
products_df.head()

# ============================================================
# VALIDACIÓN DEL MAESTRO DE PRODUCTOS
# ============================================================

# Comprobamos el número total de productos generados.
print("Número de productos:", len(products_df))

# Validamos que product_id sea único para cada producto.
print("IDs únicos:", products_df["product_id"].is_unique)


# Revisamos la distribución de productos entre las categorías.
print("\nProductos por categoría:")
print(products_df["category"].value_counts())


# Comprobamos cuántos productos están activos e inactivos.
print("\nEstado:")
print(products_df["active"].value_counts())


# Mostramos estadísticas básicas de costes y precios:
# media, desviación, mínimo, máximo y percentiles.
print("\nPrecios:")
print(products_df[["unit_cost", "base_price"]].describe())

# ============================================================
# VALIDACIÓN DE PRECIOS DE PRODUCTOS
# ============================================================

# Identificamos productos cuyo precio de venta sea menor o igual
# que su coste, lo que implicaría vender sin margen o con pérdidas.
invalid_prices = products_df[
    products_df["base_price"] <= products_df["unit_cost"]
]


# Mostramos cuántos productos presentan precios no válidos.
# En condiciones normales, el resultado esperado debería ser 0.
print(
    "Productos con precio de venta <= coste:",
    len(invalid_prices)
)

# ============================================================
# RELACIÓN ENTRE CIUDADES Y REGIONES
# ============================================================

# Definimos un diccionario que relaciona cada ciudad con su región.
# Lo utilizaremos para generar clientes con una localización coherente,
# evitando combinaciones aleatorias incorrectas entre ciudad y región.
cities_regions = {
    "Madrid": "Madrid",
    "Barcelona": "Cataluña",
    "Valencia": "Comunidad Valenciana",
    "Sevilla": "Andalucía",
    "Málaga": "Andalucía",
    "Bilbao": "País Vasco",
    "Zaragoza": "Aragón",
    "Alicante": "Comunidad Valenciana",
    "Murcia": "Región de Murcia",
    "Granada": "Andalucía",
    "Valladolid": "Castilla y León",
    "Vigo": "Galicia",
    "A Coruña": "Galicia",
    "Gijón": "Asturias",
    "Oviedo": "Asturias",
    "Palma": "Islas Baleares",
    "Las Palmas": "Canarias"
}

# ============================================================
# GENERACIÓN DEL MAESTRO DE CLIENTES
# ============================================================

# Número total de clientes que queremos generar.
NUM_CUSTOMERS = 10_000

# Listas de nombres y apellidos que utilizaremos para crear
# clientes ficticios de forma aleatoria.
first_names = [
    "Ana", "Carlos", "Laura", "David", "Lucía",
    "Javier", "Marta", "Daniel", "Sara", "Pablo",
    "Elena", "Sergio", "Paula", "Álvaro", "Irene"
]

last_names = [
    "García", "Rodríguez", "López", "Martínez",
    "Sánchez", "Pérez", "Gómez", "Fernández",
    "Díaz", "Moreno", "Muñoz", "Álvarez"
]

# Definimos los posibles segmentos de cliente y su distribución.
# La mayoría serán STANDARD, mientras que PREMIUM y VIP
# tendrán una presencia menor.
segments = ["STANDARD", "PREMIUM", "VIP"]

segment_weights = [0.75, 0.20, 0.05]

# Lista donde iremos almacenando cada cliente generado.
customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    # Generamos un identificador único con formato C00001, C00002...
    customer_id = f"C{i:05d}"

    # Seleccionamos aleatoriamente nombre y apellido.
    first_name = random.choice(first_names)
    last_name = random.choice(last_names)

    customer_name = f"{first_name} {last_name}"

    # Seleccionamos una ciudad y recuperamos su región asociada
    # para mantener coherencia geográfica.
    city = random.choice(list(cities_regions.keys()))
    region = cities_regions[city]

    # Generamos una fecha de registro aleatoria entre 2016 y 2025.
    # Limitamos el día a 28 para evitar fechas inválidas.
    registration_date = pd.Timestamp(
        random.randint(2016, 2025),
        random.randint(1, 12),
        random.randint(1, 28)
    )

    # Asignamos el segmento utilizando las probabilidades definidas.
    segment = random.choices(
        segments,
        weights=segment_weights,
        k=1
    )[0]

    # Generamos un email único utilizando nombre, apellido
    # y el identificador numérico del cliente.
    email = (
        f"{first_name.lower()}."
        f"{last_name.lower()}."
        f"{i}@example.com"
    )

    # Añadimos el cliente generado a la lista.
    customers.append(
        {
            "customer_id": customer_id,
            "customer_name": customer_name,
            "email": email,
            "city": city,
            "region": region,
            "registration_date": registration_date,
            "customer_segment": segment
        }
    )


# Convertimos la lista de clientes en un DataFrame de Pandas.
customers_df = pd.DataFrame(customers)

# Mostramos las primeras filas para validar el resultado.
customers_df.head()

# ============================================================
# VALIDACIÓN DEL MAESTRO DE CLIENTES
# ============================================================

# Comprobamos el número total de clientes generados.
print("Número de clientes:", len(customers_df))

# Validamos que customer_id sea único para cada cliente.
print("IDs únicos:", customers_df["customer_id"].is_unique)


# Revisamos la distribución de clientes por segmento.
print("\nSegmentos:")
print(customers_df["customer_segment"].value_counts())


# Comprobamos cómo se distribuyen los clientes entre las regiones.
print("\nClientes por región:")
print(customers_df["region"].value_counts())


# Mostramos estadísticas básicas de las fechas de registro,
# como la fecha mínima, máxima y valores intermedios.
print("\nFechas de alta:")
print(customers_df["registration_date"].describe())

# ============================================================
# VALIDACIONES ADICIONALES DE CLIENTES
# ============================================================

# Comprobamos si existen emails duplicados.
# El resultado esperado debería ser 0.
print(
    "Clientes con email duplicado:",
    customers_df["email"].duplicated().sum()
)


# Comprobamos si existen clientes sin fecha de registro.
# El resultado esperado también debería ser 0.
print(
    "Clientes con fechas nulas:",
    customers_df["registration_date"].isna().sum()
)

# ============================================================
# EXPORTACIÓN DE DATOS MAESTROS A CSV
# ============================================================

# Guardamos el maestro de tiendas en formato CSV.
# index=False evita exportar el índice interno del DataFrame.
stores_df.to_csv(
    STORES_PATH / "stores.csv",
    index=False
)


# Exportamos el maestro de productos.
products_df.to_csv(
    PRODUCTS_PATH / "products.csv",
    index=False
)


# Exportamos el maestro de clientes.
customers_df.to_csv(
    CUSTOMERS_PATH / "customers.csv",
    index=False
)


# Confirmamos que el proceso de exportación ha finalizado.
print("Archivos exportados correctamente")

print(list(STORES_PATH.iterdir()))
print(list(PRODUCTS_PATH.iterdir()))
print(list(CUSTOMERS_PATH.iterdir()))

from google.colab import files

files.download("/content/retail_analytics_project/data/raw/stores/stores.csv")
files.download("/content/retail_analytics_project/data/raw/products/products.csv")
files.download("/content/retail_analytics_project/data/raw/customers/customers.csv")

# ============================================================
# PARÁMETROS PARA LA GENERACIÓN DE TICKETS
# ============================================================

# Número total de tickets que queremos generar.
NUM_TICKETS = 200_000

# Definimos el periodo temporal en el que se generarán las ventas.
START_DATE = pd.Timestamp("2024-01-01")
END_DATE = pd.Timestamp("2025-12-31 23:59:59")


# Obtenemos únicamente los IDs de las tiendas físicas.
# Esta lista se utilizará posteriormente para asignar una tienda
# a los tickets generados en canal físico.
physical_stores = stores_df[
    stores_df["store_type"] == "PHYSICAL"
]["store_id"].tolist()


# Convertimos los IDs de clientes en una lista para poder
# asignarlos posteriormente de forma aleatoria a cada ticket.
customer_ids = customers_df["customer_id"].tolist()

# ============================================================
# GENERACIÓN DE TICKETS DE VENTA
# ============================================================

# Lista donde almacenaremos cada ticket generado.
tickets = []

for i in range(1, NUM_TICKETS + 1):

    # Generamos un identificador único para cada ticket.
    sale_id = f"T{i:07d}"

    # Generamos una fecha y hora aleatoria dentro del
    # periodo histórico definido anteriormente.
    total_seconds = int(
        (END_DATE - START_DATE).total_seconds()
    )

    random_seconds = random.randint(0, total_seconds)

    sale_timestamp = START_DATE + pd.Timedelta(
        seconds=random_seconds
    )

    # Aproximadamente el 10% de las ventas serán ONLINE
    # y el 90% se realizarán en tiendas físicas.
    if random.random() < 0.10:
        sales_channel = "ONLINE"
        store_id = "S999"

        # Métodos de pago disponibles para compras online.
        payment_method = random.choices(
            ["CARD", "PAYPAL", "TRANSFER"],
            weights=[0.65, 0.25, 0.10],
            k=1
        )[0]

    else:
        sales_channel = "PHYSICAL"

        # Seleccionamos aleatoriamente una tienda física.
        store_id = random.choice(physical_stores)

        # Métodos de pago disponibles en tienda física.
        payment_method = random.choices(
            ["CARD", "CASH"],
            weights=[0.80, 0.20],
            k=1
        )[0]

    # Aproximadamente el 15% de las compras serán anónimas,
    # por lo que no estarán asociadas a ningún cliente.
    if random.random() < 0.15:
        customer_id = None

    else:
        # Solo permitimos asociar clientes cuya fecha de registro
        # sea anterior o igual a la fecha de la compra.
        valid_customers = customers_df[
            customers_df["registration_date"]
            <= sale_timestamp
        ]["customer_id"]

        customer_id = (
            random.choice(valid_customers.tolist())
            if len(valid_customers) > 0
            else None
        )

    # Añadimos el ticket generado a la lista.
    tickets.append(
        {
            "sale_id": sale_id,
            "sale_timestamp": sale_timestamp,
            "store_id": store_id,
            "customer_id": customer_id,
            "sales_channel": sales_channel,
            "payment_method": payment_method
        }
    )


# Convertimos la lista de tickets en un DataFrame de Pandas.
tickets_df = pd.DataFrame(tickets)

# Mostramos las primeras filas para validar el resultado.
tickets_df.head()

print("Número de tickets:", len(tickets_df))
print("IDs únicos:", tickets_df["sale_id"].is_unique)

print("\nCanales:")
print(
    tickets_df["sales_channel"]
    .value_counts(normalize=True)
    .round(3)
)

print("\nMétodos de pago:")
print(tickets_df["payment_method"].value_counts())

print("\nClientes anónimos:")
print(
    tickets_df["customer_id"]
    .isna()
    .mean()
    .round(3)
)

print("\nRango temporal:")
print(tickets_df["sale_timestamp"].min())
print(tickets_df["sale_timestamp"].max())

# Filtramos los tickets que sean ONLINE y que, al mismo tiempo,
# tengan CASH como método de pago.
# Según nuestras reglas de negocio, esta combinación no debería existir.
invalid_online_cash = tickets_df[
    (tickets_df["sales_channel"] == "ONLINE")
    &
    (tickets_df["payment_method"] == "CASH")
]

# Mostramos cuántos registros incumplen la regla.
# El resultado esperado es 0.
print(
    "Ventas ONLINE pagadas en CASH:",
    len(invalid_online_cash)
)

"""Ahora ya sí vamos a generar las líneas de venta. Objetivo: pasar de 200.000 tickets a algo por encima de 500.000 registros, con una media aproximada de 2–3 líneas por ticket.

La lógica que vamos a seguir es:

ticket
  ↓
número de líneas
  ↓
producto por línea
  ↓
cantidad
  ↓
precio unitario
  ↓
descuento

Y mantendremos coherencia con el maestro de productos.
"""

# ============================================================
# GENERACIÓN DE LÍNEAS DE VENTA
# ============================================================

# Creamos una lista vacía donde iremos acumulando
# todas las líneas de venta generadas.
sales_lines = []

# Para mejorar el rendimiento, convertimos parte del maestro
# de productos en estructuras más rápidas de consultar.
#
# product_ids:
# Lista con todos los IDs de producto.
product_ids = products_df["product_id"].tolist()

# product_price_map:
# Diccionario cuya clave es product_id y cuyo valor es base_price.
#
# Esto evita tener que filtrar products_df cada vez que necesitamos
# consultar el precio de un producto.
product_price_map = dict(
    zip(
        products_df["product_id"],
        products_df["base_price"]
    )
)

# Recorremos cada ticket previamente generado.
for _, ticket in tickets_df.iterrows():

    # --------------------------------------------------------
    # 1. DETERMINAMOS CUÁNTAS LÍNEAS TENDRÁ EL TICKET
    # --------------------------------------------------------
    #
    # No queremos que todos los tickets tengan el mismo número
    # de líneas.
    #
    # La mayoría tendrá entre 1 y 3 productos,
    # y una pequeña proporción tendrá más.
    #
    # random.choices permite definir pesos.
    #
    # En este caso:
    # 1 línea -> 20%
    # 2 líneas -> 30%
    # 3 líneas -> 25%
    # 4 líneas -> 15%
    # 5 líneas -> 7%
    # 6 líneas -> 3%
    #
    # La media resultante será algo superior a 2,5 líneas.
    num_lines = random.choices(
        population=[1, 2, 3, 4, 5, 6],
        weights=[0.20, 0.30, 0.25, 0.15, 0.07, 0.03],
        k=1
    )[0]

    # --------------------------------------------------------
    # 2. ELEGIMOS LOS PRODUCTOS DEL TICKET
    # --------------------------------------------------------
    #
    # random.sample permite seleccionar productos sin repetirlos.
    #
    # Así evitamos que, dentro del mismo ticket, aparezca
    # dos veces el mismo product_id en líneas diferentes.
    #
    # Si alguien compra dos unidades del mismo producto,
    # eso se representará mediante quantity = 2,
    # no creando dos líneas duplicadas.
    selected_products = random.sample(
        product_ids,
        k=num_lines
    )

    # --------------------------------------------------------
    # 3. GENERAMOS CADA LÍNEA DEL TICKET
    # --------------------------------------------------------
    for line_number, product_id in enumerate(
        selected_products,
        start=1
    ):

        # ----------------------------------------------------
        # CANTIDAD VENDIDA
        # ----------------------------------------------------
        #
        # La mayoría de compras serán de una sola unidad.
        #
        # Distribución:
        # 1 unidad -> 75%
        # 2 unidades -> 18%
        # 3 unidades -> 5%
        # 4 unidades -> 1,5%
        # 5 unidades -> 0,5%
        quantity = random.choices(
            population=[1, 2, 3, 4, 5],
            weights=[0.75, 0.18, 0.05, 0.015, 0.005],
            k=1
        )[0]

        # ----------------------------------------------------
        # PRECIO UNITARIO
        # ----------------------------------------------------
        #
        # Recuperamos el precio base desde el maestro de productos.
        base_price = product_price_map[product_id]

        # En un sistema real, el precio de venta no siempre coincide
        # exactamente con el precio base.
        #
        # Puede existir:
        # - pequeña variación comercial
        # - cambio de tarifa
        # - promoción
        #
        # Aplicamos una variación aleatoria entre -5% y +5%.
        price_variation = random.uniform(
            -0.05,
            0.05
        )

        # Calculamos el precio unitario final.
        unit_price = round(
            base_price * (1 + price_variation),
            2
        )

        # ----------------------------------------------------
        # DESCUENTO
        # ----------------------------------------------------
        #
        # La mayoría de líneas no tendrán descuento.
        #
        # Usamos porcentajes habituales:
        # 0%
        # 5%
        # 10%
        # 15%
        # 20%
        #
        # El 70% aproximadamente será sin descuento.
        discount_pct = random.choices(
            population=[0.00, 0.05, 0.10, 0.15, 0.20],
            weights=[0.70, 0.10, 0.10, 0.06, 0.04],
            k=1
        )[0]

        # ----------------------------------------------------
        # CONSTRUCCIÓN DEL REGISTRO
        # --------------------------------------------------------
        #
        # Heredamos de la cabecera del ticket:
        # - sale_id
        # - sale_timestamp
        # - store_id
        # - customer_id
        # - sales_channel
        # - payment_method
        #
        # Y añadimos los atributos propios de la línea.
        sales_lines.append(
            {
                "sale_id": ticket["sale_id"],
                "line_id": line_number,
                "sale_timestamp": ticket["sale_timestamp"],
                "store_id": ticket["store_id"],
                "customer_id": ticket["customer_id"],
                "product_id": product_id,
                "quantity": quantity,
                "unit_price": unit_price,
                "discount_pct": discount_pct,
                "sales_channel": ticket["sales_channel"],
                "payment_method": ticket["payment_method"]
            }
        )

# ============================================================
# CREACIÓN DEL DATAFRAME FINAL DE SALES
# ============================================================

# Convertimos la lista de diccionarios en un DataFrame de pandas.
sales_df = pd.DataFrame(sales_lines)

# Mostramos las primeras filas para inspección visual.
sales_df.head()

# ============================================================
# VALIDACIONES BÁSICAS DE SALES
# ============================================================

# Número total de líneas generadas.
print(
    "Número de líneas de venta:",
    len(sales_df)
)

# Número de tickets únicos presentes en sales.
#
# Debería ser exactamente 200.000,
# porque todos los tickets deberían tener al menos una línea.
print(
    "Número de tickets únicos:",
    sales_df["sale_id"].nunique()
)

# Calculamos la media de líneas por ticket.
#
# Esto nos permite comprobar que la distribución
# se comporta como esperábamos.
average_lines = (
    len(sales_df)
    /
    sales_df["sale_id"].nunique()
)

print(
    "Media de líneas por ticket:",
    round(average_lines, 2)
)

# Mostramos la distribución de cantidades vendidas.
print("\nDistribución de quantity:")

print(
    sales_df["quantity"]
    .value_counts(normalize=True)
    .sort_index()
    .round(3)
)

# Mostramos la distribución de descuentos.
print("\nDistribución de descuentos:")

print(
    sales_df["discount_pct"]
    .value_counts(normalize=True)
    .sort_index()
    .round(3)
)

# ============================================================
# VALIDACIÓN DE DUPLICADOS DE PRODUCTO DENTRO DE UN TICKET
# ============================================================

# Buscamos combinaciones repetidas de:
# sale_id + product_id
#
# Nuestra regla es que un producto solo puede aparecer
# una vez por ticket.
#
# Si se compran varias unidades, se refleja en quantity.
duplicated_products = sales_df.duplicated(
    subset=["sale_id", "product_id"]
).sum()

print(
    "Productos duplicados dentro del mismo ticket:",
    duplicated_products
)

# ============================================================
# VALIDACIONES CRUZADAS ENTRE SALES Y LOS MAESTROS
# ============================================================

# ------------------------------------------------------------
# 1. VALIDACIÓN DE STORE_ID
# ------------------------------------------------------------
#
# Queremos comprobar que todos los store_id presentes en sales
# existen realmente en el maestro stores.
#
# isin(...) devuelve True si el valor existe en la lista indicada.
# Con ~ invertimos el resultado para quedarnos con los NO encontrados.

invalid_stores = sales_df[
    ~sales_df["store_id"].isin(stores_df["store_id"])
]

print(
    "Líneas con store_id inexistente:",
    len(invalid_stores)
)


# ------------------------------------------------------------
# 2. VALIDACIÓN DE PRODUCT_ID
# ------------------------------------------------------------
#
# Mismo concepto que antes, pero comprobando productos.
#
# Toda línea de venta debe hacer referencia a un producto válido.

invalid_products = sales_df[
    ~sales_df["product_id"].isin(products_df["product_id"])
]

print(
    "Líneas con product_id inexistente:",
    len(invalid_products)
)


# ------------------------------------------------------------
# 3. VALIDACIÓN DE CUSTOMER_ID
# ------------------------------------------------------------
#
# Aquí la lógica cambia ligeramente.
#
# customer_id puede ser:
# - un cliente válido existente en customers
# - NULL, porque permitimos compras anónimas
#
# Por tanto, solo consideramos inválido un customer_id:
# - que NO sea NULL
# - y que NO exista en customers

invalid_customers = sales_df[
    sales_df["customer_id"].notna()
    &
    ~sales_df["customer_id"].isin(customers_df["customer_id"])
]

print(
    "Líneas con customer_id inexistente:",
    len(invalid_customers)
)

# ============================================================
# VALIDACIÓN TEMPORAL DE CLIENTES
# ============================================================

# Para comprobar que un cliente no compra antes de registrarse,
# necesitamos traer registration_date desde customers hacia sales.
#
# Hacemos un merge LEFT:
#
# sales_df es nuestra tabla principal.
# customers_df aporta únicamente:
# - customer_id
# - registration_date
#
# LEFT garantiza que no eliminamos ninguna línea de venta.

sales_customer_check = sales_df.merge(
    customers_df[
        ["customer_id", "registration_date"]
    ],
    on="customer_id",
    how="left"
)

# ------------------------------------------------------------
# Consideramos inválida una venta si:
#
# 1. customer_id NO es NULL
# 2. sale_timestamp es anterior a registration_date
#
# Las ventas anónimas quedan fuera de esta regla porque
# obviamente no tienen fecha de registro asociada.

invalid_customer_dates = sales_customer_check[
    sales_customer_check["customer_id"].notna()
    &
    (
        sales_customer_check["sale_timestamp"]
        <
        sales_customer_check["registration_date"]
    )
]

print(
    "Líneas con compra anterior al registro del cliente:",
    len(invalid_customer_dates)
)

# ============================================================
# VALIDACIÓN TEMPORAL DE TIENDAS
# ============================================================

# Añadimos opening_date del maestro stores a cada línea de venta.
#
# Nuevamente utilizamos un LEFT JOIN para conservar todas
# las ventas aunque existiera alguna inconsistencia.

sales_store_check = sales_df.merge(
    stores_df[
        ["store_id", "opening_date"]
    ],
    on="store_id",
    how="left"
)

# ------------------------------------------------------------
# Una venta sería inválida si ocurrió antes de que la tienda
# estuviera abierta.
#
# Ejemplo:
#
# opening_date     = 2022-05-20
# sale_timestamp   = 2021-03-15
#
# Eso sería imposible según nuestro modelo de negocio.

invalid_store_dates = sales_store_check[
    sales_store_check["sale_timestamp"]
    <
    sales_store_check["opening_date"]
]

print(
    "Líneas con venta anterior a apertura de tienda:",
    len(invalid_store_dates)
)

# ============================================================
# RESUMEN DE VALIDACIONES
# ============================================================

validation_results = {
    "store_id inexistente": len(invalid_stores),
    "product_id inexistente": len(invalid_products),
    "customer_id inexistente": len(invalid_customers),
    "venta antes de registro cliente": len(invalid_customer_dates),
    "venta antes de apertura tienda": len(invalid_store_dates)
}

# Mostramos cada validación de forma legible.
for validation, errors in validation_results.items():
    print(
        f"{validation}: {errors}"
    )

# ============================================================
# EXPORTACIÓN DE SALES EN ARCHIVOS DIARIOS
# ============================================================

# Creamos una copia del DataFrame para trabajar sobre ella
# sin modificar accidentalmente sales_df.
sales_export_df = sales_df.copy()

# ------------------------------------------------------------
# 1. ASEGURAMOS QUE SALE_TIMESTAMP ES DATETIME
# ------------------------------------------------------------
#
# Aunque ya debería ser datetime, esta conversión explícita
# evita problemas si en algún momento el DataFrame ha sido
# serializado o reconstruido.
sales_export_df["sale_timestamp"] = pd.to_datetime(
    sales_export_df["sale_timestamp"]
)

# ------------------------------------------------------------
# 2. CREAMOS UNA COLUMNA AUXILIAR CON LA FECHA
# ------------------------------------------------------------
#
# Esta columna contiene únicamente la parte de fecha:
#
# 2024-03-15 18:34:22
#        ↓
# 2024-03-15
#
# Nos servirá para agrupar todas las líneas de un mismo día
# dentro del mismo archivo.
sales_export_df["sale_date"] = (
    sales_export_df["sale_timestamp"].dt.date
)

# ------------------------------------------------------------
# 3. AGRUPAMOS SALES POR DÍA
# ------------------------------------------------------------
#
# Cada grupo contendrá todas las líneas de venta
# correspondientes a una fecha concreta.
#
# Ejemplo:
#
# 2024-01-01 -> todas las ventas del día
# 2024-01-02 -> todas las ventas del día
# ...
daily_groups = sales_export_df.groupby("sale_date")

# Contador para saber cuántos archivos generamos.
generated_files = 0

# Contador para comprobar cuántas filas hemos exportado.
exported_rows = 0

# ------------------------------------------------------------
# 4. RECORREMOS CADA DÍA
# ------------------------------------------------------------

for sale_date, daily_df in daily_groups:

    # Convertimos sale_date a Timestamp para poder acceder
    # cómodamente a year, month y day.
    current_date = pd.Timestamp(sale_date)

    year = current_date.year
    month = current_date.month
    day = current_date.day

    # --------------------------------------------------------
    # 5. CONSTRUIMOS LA ESTRUCTURA DE CARPETAS
    # --------------------------------------------------------
    #
    # El resultado será:
    #
    # sales/
    # ├── year=2024/
    # │   ├── month=01/
    # │   │   ├── sales_2024_01_01.csv
    #
    # Usamos :02d para que enero sea "01" y no "1".
    output_folder = (
        SALES_PATH
        / f"year={year}"
        / f"month={month:02d}"
    )

    # Creamos las carpetas si todavía no existen.
    #
    # parents=True:
    # crea también las carpetas padre necesarias.
    #
    # exist_ok=True:
    # no da error si la carpeta ya existe.
    output_folder.mkdir(
        parents=True,
        exist_ok=True
    )

    # --------------------------------------------------------
    # 6. CONSTRUIMOS EL NOMBRE DEL ARCHIVO
    # --------------------------------------------------------

    file_name = (
        f"sales_{year}_{month:02d}_{day:02d}.csv"
    )

    file_path = output_folder / file_name

    # --------------------------------------------------------
    # 7. ELIMINAMOS LA COLUMNA AUXILIAR SALE_DATE
    # --------------------------------------------------------
    #
    # sale_date solo la hemos utilizado para agrupar.
    #
    # No queremos incluirla en el archivo porque ya disponemos
    # de sale_timestamp y podemos derivar la fecha posteriormente.
    daily_export_df = daily_df.drop(
        columns=["sale_date"]
    )

    # --------------------------------------------------------
    # 8. EXPORTAMOS EL CSV
    # --------------------------------------------------------
    #
    # index=False evita que pandas escriba una columna adicional
    # con el índice del DataFrame.
    daily_export_df.to_csv(
        file_path,
        index=False
    )

    # Actualizamos nuestros contadores.
    generated_files += 1
    exported_rows += len(daily_export_df)


# ------------------------------------------------------------
# 9. MOSTRAMOS RESULTADOS
# ------------------------------------------------------------

print(
    "Archivos diarios generados:",
    generated_files
)

print(
    "Filas exportadas:",
    exported_rows
)

print(
    "Filas originales:",
    len(sales_df)
)

# ============================================================
# VALIDACIÓN 1: COMPROBAR QUE NO PERDIMOS FILAS
# ============================================================

# Compararemos el número de filas originales con el número
# acumulado de filas que hemos escrito en los CSV.

if exported_rows == len(sales_df):
    print("OK - Todas las filas fueron exportadas")
else:
    print("ERROR - El número de filas no coincide")

# ============================================================
# VALIDACIÓN 2: RELECTURA DE TODOS LOS ARCHIVOS GENERADOS
# ============================================================

# rglob busca archivos de forma recursiva dentro de SALES_PATH.
#
# El patrón "*.csv" significa:
# "encuentra cualquier archivo CSV en cualquier subcarpeta".
sales_files = list(
    SALES_PATH.rglob("*.csv")
)

print(
    "CSV encontrados:",
    len(sales_files)
)

# ------------------------------------------------------------
# Leemos cada CSV generado.
# ------------------------------------------------------------
#
# Creamos una lista de DataFrames y posteriormente
# los concatenamos.
reloaded_dfs = []

for file_path in sales_files:

    df_temp = pd.read_csv(file_path)

    reloaded_dfs.append(df_temp)

# Unimos todos los archivos diarios en un único DataFrame.
sales_reloaded_df = pd.concat(
    reloaded_dfs,
    ignore_index=True
)

print(
    "Filas recuperadas:",
    len(sales_reloaded_df)
)

print(
    "Filas originales:",
    len(sales_df)
)

# ============================================================
# VALIDACIÓN FINAL
# ============================================================

if len(sales_reloaded_df) == len(sales_df):
    print(
        "OK - Los CSV diarios contienen todas las ventas"
    )
else:
    print(
        "ERROR - Hay diferencias entre origen y archivos"
    )

# ============================================================
# COMPRIMIR TODOS LOS CSV DE SALES EN UN ÚNICO ZIP
# ============================================================

# Importamos shutil, que permite trabajar con archivos y carpetas.
import shutil

# Ruta base donde queremos crear el ZIP.
#
# El resultado será:
# /content/sales_daily_files.zip
zip_path = "/content/sales_daily_files"

# ------------------------------------------------------------
# make_archive crea un archivo comprimido.
#
# Primer parámetro:
# nombre/ruta del archivo SIN extensión.
#
# Segundo parámetro:
# formato de compresión -> "zip"
#
# root_dir:
# carpeta que queremos comprimir.
# ------------------------------------------------------------
shutil.make_archive(
    zip_path,
    "zip",
    root_dir=SALES_PATH
)

print(
    "ZIP generado:",
    zip_path + ".zip"
)

# ============================================================
# DESCARGAR EL ZIP AL ORDENADOR
# ============================================================

# Importamos la utilidad de descarga propia de Google Colab.
from google.colab import files

# Esto abrirá la descarga en el navegador.
files.download(
    "/content/sales_daily_files.zip"
)

# ============================================================
# GENERACIÓN INCREMENTAL DE SALES 2026
# ENERO -> JULIO
# ============================================================
#
# OBJETIVO
# ------------------------------------------------------------
#
# Generar nuevos datos de ventas correspondientes al periodo:
#
#       2026-01-01 -> 2026-07-31
#
# manteniendo exactamente la misma lógica de negocio utilizada
# para los datos históricos 2024-2025.
#
# IMPORTANTE:
#
# - NO regeneramos los maestros.
# - NO modificamos los CSV históricos.
# - Reutilizamos:
#       stores_df
#       customers_df
#       products_df
#
# - Los sale_id comienzan en T0200001 para evitar colisiones
#   con los 200.000 tickets históricos.
#
# ============================================================


from pathlib import Path
import pandas as pd
import numpy as np
import random
import shutil


# ============================================================
# 1. CONFIGURACIÓN DE LA CARGA INCREMENTAL
# ============================================================

# Utilizamos una semilla diferente para que la generación 2026
# sea reproducible pero distinta al histórico original.
INCREMENTAL_SEED = 2026

random.seed(INCREMENTAL_SEED)
np.random.seed(INCREMENTAL_SEED)


# Periodo que queremos incorporar como nueva carga.
START_DATE_2026 = pd.Timestamp("2026-01-01 00:00:00")
END_DATE_2026 = pd.Timestamp("2026-07-31 23:59:59")


# ------------------------------------------------------------
# NÚMERO DE TICKETS
# ------------------------------------------------------------
#
# El histórico contiene:
#
#   200.000 tickets / 731 días ≈ 274 tickets diarios
#
# Enero-julio 2026 son aproximadamente 212 días.
#
# Manteniendo un volumen parecido:
#
#   212 × 274 ≈ 58.000 tickets
#
# ------------------------------------------------------------

NUM_TICKETS_2026 = 58_000


# ------------------------------------------------------------
# PRIMER ID DEL NUEVO PERIODO
# ------------------------------------------------------------
#
# Histórico:
#
# T0000001 ... T0200000
#
# Incremental:
#
# T0200001 ...
#
# ------------------------------------------------------------

FIRST_SALE_NUMBER_2026 = 200_001


print("=" * 70)
print("GENERACIÓN INCREMENTAL 2026")
print("=" * 70)

print("Periodo:", START_DATE_2026, "->", END_DATE_2026)
print("Tickets a generar:", NUM_TICKETS_2026)
print()


# ============================================================
# 2. PREPARACIÓN DE MAESTROS
# ============================================================

# Recuperamos únicamente las tiendas físicas.
physical_stores_2026 = (
    stores_df[
        stores_df["store_type"] == "PHYSICAL"
    ]["store_id"]
    .tolist()
)


# Lista de productos disponibles.
product_ids_2026 = (
    products_df["product_id"]
    .tolist()
)


# Diccionario:
#
# product_id -> base_price
#
# Nos evita consultar products_df continuamente.
product_price_map_2026 = dict(
    zip(
        products_df["product_id"],
        products_df["base_price"]
    )
)


# ============================================================
# 3. GENERACIÓN DE TICKETS 2026
# ============================================================

tickets_2026 = []


# Calculamos una sola vez la duración total del periodo.
total_seconds_2026 = int(
    (
        END_DATE_2026
        -
        START_DATE_2026
    ).total_seconds()
)


for i in range(NUM_TICKETS_2026):

    # --------------------------------------------------------
    # SALE_ID
    # --------------------------------------------------------

    sale_number = (
        FIRST_SALE_NUMBER_2026
        +
        i
    )

    sale_id = f"T{sale_number:07d}"


    # --------------------------------------------------------
    # TIMESTAMP DE LA VENTA
    # --------------------------------------------------------

    random_seconds = random.randint(
        0,
        total_seconds_2026
    )

    sale_timestamp = (
        START_DATE_2026
        +
        pd.Timedelta(
            seconds=random_seconds
        )
    )


    # --------------------------------------------------------
    # CANAL DE VENTA
    # --------------------------------------------------------
    #
    # Mantenemos la distribución histórica:
    #
    # ONLINE   ≈ 10%
    # PHYSICAL ≈ 90%
    #
    # --------------------------------------------------------

    if random.random() < 0.10:

        sales_channel = "ONLINE"

        # Todas las ventas online pertenecen a la tienda virtual.
        store_id = "S999"


        # Métodos de pago ONLINE:
        #
        # CARD     65%
        # PAYPAL   25%
        # TRANSFER 10%

        payment_method = random.choices(
            ["CARD", "PAYPAL", "TRANSFER"],
            weights=[0.65, 0.25, 0.10],
            k=1
        )[0]

    else:

        sales_channel = "PHYSICAL"

        store_id = random.choice(
            physical_stores_2026
        )


        # Métodos de pago PHYSICAL:
        #
        # CARD 80%
        # CASH 20%

        payment_method = random.choices(
            ["CARD", "CASH"],
            weights=[0.80, 0.20],
            k=1
        )[0]


    # --------------------------------------------------------
    # CLIENTE
    # --------------------------------------------------------
    #
    # Aproximadamente el 15% de las ventas serán anónimas.
    #
    # --------------------------------------------------------

    if random.random() < 0.15:

        customer_id = None

    else:

        # Solo permitimos clientes registrados antes de la compra.

        valid_customers = customers_df[
            customers_df["registration_date"]
            <= sale_timestamp
        ]["customer_id"]

        customer_id = (
            random.choice(
                valid_customers.tolist()
            )
            if len(valid_customers) > 0
            else None
        )


    # --------------------------------------------------------
    # REGISTRO DEL TICKET
    # --------------------------------------------------------

    tickets_2026.append(
        {
            "sale_id": sale_id,
            "sale_timestamp": sale_timestamp,
            "store_id": store_id,
            "customer_id": customer_id,
            "sales_channel": sales_channel,
            "payment_method": payment_method
        }
    )


# Convertimos los tickets a DataFrame.
tickets_2026_df = pd.DataFrame(
    tickets_2026
)


# ============================================================
# 4. GENERACIÓN DE LÍNEAS DE VENTA
# ============================================================

sales_lines_2026 = []


for _, ticket in tickets_2026_df.iterrows():

    # --------------------------------------------------------
    # NÚMERO DE LÍNEAS DEL TICKET
    # --------------------------------------------------------

    num_lines = random.choices(
        population=[
            1,
            2,
            3,
            4,
            5,
            6
        ],
        weights=[
            0.20,
            0.30,
            0.25,
            0.15,
            0.07,
            0.03
        ],
        k=1
    )[0]


    # Elegimos productos diferentes dentro del mismo ticket.
    selected_products = random.sample(
        product_ids_2026,
        k=num_lines
    )


    for line_number, product_id in enumerate(
        selected_products,
        start=1
    ):

        # ----------------------------------------------------
        # QUANTITY
        # ----------------------------------------------------

        quantity = random.choices(
            population=[
                1,
                2,
                3,
                4,
                5
            ],
            weights=[
                0.75,
                0.18,
                0.05,
                0.015,
                0.005
            ],
            k=1
        )[0]


        # ----------------------------------------------------
        # PRECIO UNITARIO
        # ----------------------------------------------------

        base_price = (
            product_price_map_2026[
                product_id
            ]
        )


        # Permitimos una variación comercial de ±5%.
        price_variation = random.uniform(
            -0.05,
            0.05
        )


        unit_price = round(
            base_price
            *
            (
                1
                +
                price_variation
            ),
            2
        )


        # ----------------------------------------------------
        # DESCUENTO
        # ----------------------------------------------------

        discount_pct = random.choices(
            population=[
                0.00,
                0.05,
                0.10,
                0.15,
                0.20
            ],
            weights=[
                0.70,
                0.10,
                0.10,
                0.06,
                0.04
            ],
            k=1
        )[0]


        # ----------------------------------------------------
        # REGISTRO FINAL
        # ----------------------------------------------------

        sales_lines_2026.append(
            {
                "sale_id": ticket["sale_id"],
                "line_id": line_number,
                "sale_timestamp": ticket["sale_timestamp"],
                "store_id": ticket["store_id"],
                "customer_id": ticket["customer_id"],
                "product_id": product_id,
                "quantity": quantity,
                "unit_price": unit_price,
                "discount_pct": discount_pct,
                "sales_channel": ticket["sales_channel"],
                "payment_method": ticket["payment_method"]
            }
        )


# ============================================================
# 5. DATAFRAME SALES 2026
# ============================================================

sales_2026_df = pd.DataFrame(
    sales_lines_2026
)


# ============================================================
# 6. VALIDACIONES
# ============================================================

print("=" * 70)
print("VALIDACIÓN SALES 2026")
print("=" * 70)


print(
    "Tickets generados:",
    tickets_2026_df["sale_id"].nunique()
)


print(
    "Líneas generadas:",
    len(sales_2026_df)
)


print(
    "Media líneas/ticket:",
    round(
        len(sales_2026_df)
        /
        sales_2026_df["sale_id"].nunique(),
        2
    )
)


print(
    "Primer sale_id:",
    sales_2026_df["sale_id"].min()
)


print(
    "Último sale_id:",
    sales_2026_df["sale_id"].max()
)


print(
    "Fecha mínima:",
    sales_2026_df["sale_timestamp"].min()
)


print(
    "Fecha máxima:",
    sales_2026_df["sale_timestamp"].max()
)


# ------------------------------------------------------------
# DUPLICADOS DE CLAVE
# ------------------------------------------------------------

duplicate_keys_2026 = (
    sales_2026_df
    .duplicated(
        subset=[
            "sale_id",
            "line_id"
        ]
    )
    .sum()
)


print(
    "Duplicados sale_id + line_id:",
    duplicate_keys_2026
)


# ------------------------------------------------------------
# PRODUCTOS DUPLICADOS DENTRO DEL TICKET
# ------------------------------------------------------------

duplicate_products_2026 = (
    sales_2026_df
    .duplicated(
        subset=[
            "sale_id",
            "product_id"
        ]
    )
    .sum()
)


print(
    "Productos duplicados dentro del ticket:",
    duplicate_products_2026
)


# ------------------------------------------------------------
# CLIENTES ANÓNIMOS
# ------------------------------------------------------------

anonymous_pct_2026 = (
    tickets_2026_df["customer_id"]
    .isna()
    .mean()
    *
    100
)


print(
    "Tickets anónimos:",
    round(
        anonymous_pct_2026,
        2
    ),
    "%"
)


# ------------------------------------------------------------
# CANALES
# ------------------------------------------------------------

print("\nDistribución de canales:")

print(
    tickets_2026_df[
        "sales_channel"
    ]
    .value_counts(
        normalize=True
    )
    .mul(100)
    .round(2)
)


# ------------------------------------------------------------
# REGLA ONLINE + CASH
# ------------------------------------------------------------

invalid_online_cash_2026 = (
    tickets_2026_df[
        (
            tickets_2026_df["sales_channel"]
            ==
            "ONLINE"
        )
        &
        (
            tickets_2026_df["payment_method"]
            ==
            "CASH"
        )
    ]
)


print(
    "\nONLINE + CASH inválidos:",
    len(
        invalid_online_cash_2026
    )
)


# ============================================================
# 7. EXPORTACIÓN DIARIA
# ============================================================

sales_2026_export_df = (
    sales_2026_df.copy()
)


sales_2026_export_df[
    "sale_timestamp"
] = pd.to_datetime(
    sales_2026_export_df[
        "sale_timestamp"
    ]
)


sales_2026_export_df[
    "sale_date"
] = (
    sales_2026_export_df[
        "sale_timestamp"
    ]
    .dt.date
)


generated_files_2026 = 0
exported_rows_2026 = 0


for sale_date, daily_df in (
    sales_2026_export_df
    .groupby("sale_date")
):

    current_date = pd.Timestamp(
        sale_date
    )

    year = current_date.year
    month = current_date.month
    day = current_date.day


    # --------------------------------------------------------
    # ESTRUCTURA:
    #
    # sales/
    # └── year=2026/
    #     ├── month=01/
    #     ├── month=02/
    #     ...
    #     └── month=07/
    #
    # --------------------------------------------------------

    output_folder = (
        SALES_PATH
        /
        f"year={year}"
        /
        f"month={month:02d}"
    )


    output_folder.mkdir(
        parents=True,
        exist_ok=True
    )


    file_name = (
        f"sales_{year}_"
        f"{month:02d}_"
        f"{day:02d}.csv"
    )


    file_path = (
        output_folder
        /
        file_name
    )


    daily_export_df = (
        daily_df
        .drop(
            columns=[
                "sale_date"
            ]
        )
    )


    daily_export_df.to_csv(
        file_path,
        index=False
    )


    generated_files_2026 += 1
    exported_rows_2026 += len(
        daily_export_df
    )


# ============================================================
# 8. VALIDACIÓN DE EXPORTACIÓN
# ============================================================

print()
print("=" * 70)
print("EXPORTACIÓN 2026")
print("=" * 70)


print(
    "Archivos diarios generados:",
    generated_files_2026
)


print(
    "Filas exportadas:",
    exported_rows_2026
)


print(
    "Filas originales:",
    len(sales_2026_df)
)


if (
    exported_rows_2026
    ==
    len(sales_2026_df)
):

    print(
        "OK - Todas las filas 2026 fueron exportadas"
    )

else:

    print(
        "ERROR - El número de filas no coincide"
    )


# ============================================================
# 9. CREACIÓN DE ZIP SOLO CON 2026
# ============================================================

SALES_2026_PATH = (
    SALES_PATH
    /
    "year=2026"
)


zip_path_2026 = (
    "/content/sales_incremental_2026_Jan_Jul"
)


shutil.make_archive(
    zip_path_2026,
    "zip",
    root_dir=SALES_2026_PATH
)


print(
    "\nZIP generado:",
    zip_path_2026 + ".zip"
)


# ============================================================
# 10. DESCARGA
# ============================================================

from google.colab import files


files.download(
    zip_path_2026 + ".zip"
)